require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  AutoCorrect: true
  Max: 80

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "config/deploy.rb"
    - "config/environments/*"
    - "config/routes.rb"
    - "db/migrate/*"
    - "**/*_spec.rb"
    - "**/*.rake"
    - "spec/factories.rb"
    - "spec/rails_helper.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Style/FormatStringToken:
  Exclude:
    - "config/routes.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Rails/ContentTag:
  Exclude:
    - 'app/form_builders/sugar/form_builder.rb'
    - 'app/helpers/icons_helper.rb'
    - 'app/helpers/posts_helper.rb'
    - 'config/puma.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20080701172614_create_exchange_views.rb'
    - 'db/migrate/20090404154958_create_discussion_relationships.rb'
    - 'db/migrate/20210511201335_create_active_storage_variant_records.active_storage.rb'

Rails/DynamicFindBy:
  AllowedReceivers:
    - Emoji

RSpec:
  Language:
    Expectations:
      - user_is_logged_in
    Includes:
      Examples:
        - it_requires_admin_for
        - it_requires_authentication_for
        - it_requires_login_for
        - it_requires_moderator_for
        - it_requires_user_admin_for
