require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
    - "config/routes.rb"
    - "db/migrate/*"
    - "**/*_spec.rb"
    - "spec/factories.rb"
    - "spec/rails_helper.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Rails:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_alias
    - find_by_sql

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20080701172614_create_exchange_views.rb'
    - 'db/migrate/20090404154958_create_discussion_relationships.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/filters/renderer.rb'
    - 'app/helpers/posts_helper.rb'

Rails/SkipsModelValidations:
  Blacklist:
    - decrement!
    - decrement_counter
    - increment!
    - increment_counter
    - toggle!
    - touch
    - update_attribute
    - update_column
    - update_columns
    - update_counters

RSpec/EmptyExampleGroup:
  CustomIncludeMethods:
    - 'it_requires_login_for'
