require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Rails:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20080701172614_create_exchange_views.rb'
    - 'db/migrate/20090404154958_create_discussion_relationships.rb'

Rails/BulkChangeTable:
  Enabled: false

RSpec/EmptyExampleGroup:
  CustomIncludeMethods:
    - 'it_requires_login_for'
