require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
    - "config/routes.rb"
    - "db/migrate/*"
    - "**/*_spec.rb"
    - "spec/factories.rb"
    - "spec/rails_helper.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Style/FormatStringToken:
  Exclude:
    - "config/routes.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20080701172614_create_exchange_views.rb'
    - 'db/migrate/20090404154958_create_discussion_relationships.rb'

Rails/DynamicFindBy:
  AllowedReceivers:
    - Emoji

RSpec:
  Language:
    Includes:
      Examples:
        - it_requires_admin_for
        - it_requires_authentication_for
        - it_requires_login_for
        - it_requires_moderator_for
        - it_requires_user_admin_for
