defaults: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV.fetch("SUGAR_DB_HOST",     "localhost") %>
  username: <%= ENV.fetch("SUGAR_DB_USERNAME", "rails") %>
  password: <%= ENV.fetch("SUGAR_DB_PASSWORD", "") %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout:   5000

development:
  database: <%= ENV.fetch("SUGAR_DB_DATABASE", "sugar_development") %>
  <<: *default

test:
  database: <%= ENV.fetch("SUGAR_DB_DATABASE", "sugar_test") %>
  <<: *default

production:
  database: <%= ENV.fetch("SUGAR_DB_DATABASE", "sugar_production") %>
  <<: *default
