defaults: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("SUGAR_DB_HOST", "localhost") %>
  username: <%= ENV.fetch("SUGAR_DB_USERNAME", "rails") %>
  password: <%= ENV.fetch("SUGAR_DB_PASSWORD", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("SUGAR_DB_DATABASE", "sugar_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("SUGAR_DB_DATABASE", "sugar_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("SUGAR_DB_DATABASE", "sugar_production") %>
  prepared_statements: false
