[SERVICE]
    Flush            5
    Daemon           Off
    Log_Level        info
    Parsers_File     parsers.conf
    Parsers_File     fluent-bit-parsers.conf

[INPUT]
    Name             tail
    Tag              docker.*
    Path             /var/lib/docker/containers/*/*.log
    Parser           docker
    DB               /fluent-bit/state/tail.db
    Mem_Buf_Limit    16MB
    Skip_Long_Lines  On
    Refresh_Interval 10

[FILTER]
    Name             parser
    Match            docker.*
    Key_Name         log
    Parser           app_json
    Reserve_Data     On

[FILTER]
    Name             modify
    Match            docker.*
    Condition        Key_exists application
    Condition        Key_does_not_exist source
    Add              source rails

[FILTER]
    Name             modify
    Match            docker.*
    Condition        Key_does_not_exist source
    Add              source system

[OUTPUT]
    Name             http
    Match            *
    Host             b3s-victorialogs
    Port             9428
    URI              /insert/jsonline?_stream_fields=source&_msg_field=message,path,log&_time_field=time
    Format           json_lines
    Json_date_format iso8601
    Compress         gzip
