---
production:
  reactivate_eligible_users:
    class: ReactivateEligibleUsersJob
    schedule: every hour
  cleanup_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(finished_before: 30.days.ago)"
    schedule: every day at 2am
# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
