production:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST", "localhost") %>
    port: <%= ENV.fetch("SOLR_PORT", "8980") %>
    log_level: WARNING
    path: <%= ENV.fetch("SOLR_PATH", "/solr") %>
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST", "localhost") %>
    port: <%= ENV.fetch("SOLR_PORT", "8982") %>
    log_level: INFO
    path: <%= ENV.fetch("SOLR_PATH", "/solr/development") %>

test:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST", "localhost") %>
    port: <%= ENV.fetch("SOLR_PORT", "8981") %>
    log_level: WARNING
    path: <%= ENV.fetch("SOLR_PATH", "/solr/test") %>
