env:
  RUBY_VERSION: 2.7
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: sugar_test
  CC_TEST_REPORTER_ID: 486bb0a91d51ad96ec90a47dced78f74bfe54ae9b913ac83fa48d69703e3f66d

name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: gem install rubocop rubocop-rails rubocop-rspec
      - name: Check code
        run: rubocop

  # eslint-test:
  #   name: ESLint
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   if: "!contains(github.event.head_commit.message, '[ci skip]')"
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Node modules cache
  #       uses: actions/cache@v1
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-
  #     - name: Install Node modules
  #       run: |
  #         yarn install
  #     - name: Check code
  #       run: yarn lint-javascript

  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        sugar_db: ["postgresql", "mysql"]
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Ruby gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      # - name: Node modules cache
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      # - name: Install Node modules
      #   run: |
      #     yarn install
      - name: Verify MySQL connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Create database
        env:
          # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAILS_ENV: test
          SUGAR_DB: ${{ matrix.sugar_db }}
          SUGAR_DB_HOST: 127.0.0.1
          SUGAR_DB_USERNAME: ${{ env.DB_USER }}
          SUGAR_DB_PASSWORD: ${{ env.DB_PASSWORD }}
          REDIS_URL: redis://localhost:6379/1
        run: |
          bin/rails db:migrate
      - name: Start Solr
        env:
          RAILS_ENV: test
        run: |
          bin/rails sunspot:solr:start RAILS_ENV=test
      - name: Run tests
        env:
          # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          SUGAR_DB: ${{ matrix.sugar_db }}
          SUGAR_DB_HOST: 127.0.0.1
          SUGAR_DB_USERNAME: ${{ env.DB_USER }}
          SUGAR_DB_PASSWORD: ${{ env.DB_PASSWORD }}
          REDIS_URL: redis://localhost:6379/1
        run: bundle exec rspec
      - name: Send results to Code Climate
        uses: paambaati/codeclimate-action@v2.6.0
        if: ${{ env.CC_TEST_REPORTER_ID }}
        env:
          CC_TEST_REPORTER_ID: ${{ env.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: ls
