---
name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        default: production
        type: string
      sentry_project:
        required: true
        type: string
jobs:
  kamal:
    name: Kamal
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      VERSION: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Deploy with kamal
        run: |
          bundle exec kamal deploy --version=$VERSION

  sentry:
    name: Sentry
    runs-on: ubuntu-latest
    needs:
      - kamal
    steps:
      - uses: actions/checkout@v4
      - name: Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: b3s
          SENTRY_PROJECT: ${{ inputs.sentry_project }}
        with:
          environment: ${{ inputs.environment }}
