---
name: Push
on:
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: "Test"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    uses: ./.github/workflows/test.yml
    with:
      postgres_db: sugar_test
    secrets: inherit

  deploy:
    name: "Deploy"
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[deploy skip]')
    needs:
      - test
    uses: ./.github/workflows/deploy.yml
    with:
      sentry_project: b3s
    secrets: inherit
